(function webpackUniversalModuleDefinition(root,factory){if(typeof exports==='object'&&typeof module==='object')
	module.exports=factory();else if(typeof define==='function'&&define.amd)
	define([],factory);else if(typeof exports==='object')
	exports["Parallax"]=factory();else
	root["Parallax"]=factory();})(this,function(){return(function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])
	return installedModules[moduleId].exports;var module=installedModules[moduleId]={exports:{},id:moduleId,loaded:false};modules[moduleId].call(module.exports,module,module.exports,__webpack_require__);module.loaded=true;return module.exports;}
	__webpack_require__.m=modules;__webpack_require__.c=installedModules;__webpack_require__.p="";return __webpack_require__(0);})([function(module,exports,__webpack_require__){'use strict';Object.defineProperty(exports,'__esModule',{value:true});var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{'default':obj};}
	function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function');}}
	var _helpersHelpers=__webpack_require__(1);var _Stage=__webpack_require__(2);var _Stage2=_interopRequireDefault(_Stage);var _Canvas=__webpack_require__(4);var _Canvas2=_interopRequireDefault(_Canvas);var _riotObservable=__webpack_require__(3);var _riotObservable2=_interopRequireDefault(_riotObservable);var stage;var Parallax=(function(){function Parallax(selector){var opts=arguments.length<=1||arguments[1]===undefined?{}:arguments[1];_classCallCheck(this,Parallax);(0,_riotObservable2['default'])(this);this.opts=opts;this.selector=selector;this.canvases=[];this.add(selector);if(!stage)stage=new _Stage2['default']();return this;}
		_createClass(Parallax,[{key:'init',value:function init(){if(!this.canvases.length){console.warn('No images were found with the selector "'+this.selector+'"');}else{this.imagesLoaded=0;this.bind();}
			return this;}},{key:'bind',value:function bind(){var _this=this;this._onResize=function(){for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}
			return _this.resize.apply(_this,args);};this._onScroll=function(){for(var _len2=arguments.length,args=Array(_len2),_key2=0;_key2<_len2;_key2++){args[_key2]=arguments[_key2];}
			return _this.scroll.apply(_this,args);};stage.on('resize',this._onResize);stage.on('scroll',this._onScroll);this.canvases.forEach(function(canvas){canvas.one('loaded',function(){return _this.onCanvasLoaded(canvas);});canvas.load();});return this;}},{key:'refresh',value:function refresh(){this.onResize(stage.size).onScroll(stage.scrollTop);return this;}},{key:'onCanvasLoaded',value:function onCanvasLoaded(canvas){this.trigger('image:loaded',canvas.img,canvas);this.imagesLoaded++;canvas.draw(stage);if(this.imagesLoaded==this.canvases.length)this.trigger('images:loaded');return this;}},{key:'scroll',value:function scroll(scrollTop){var i=this.canvases.length,offsetYBounds=this.opts.offsetYBounds,stageScrollTop=stage.scrollTop;while(i--){var canvas=this.canvases[i],canvasHeight=canvas.size.height,canvasOffset=canvas.offset,canvasScrollDelta=canvasOffset.top+canvasHeight-stageScrollTop;if(canvas.isLoaded&&canvasScrollDelta+offsetYBounds>0&&canvasScrollDelta-offsetYBounds<stageScrollTop+stage.height){canvas.draw(stage);this.trigger('draw',canvas.img);}}
			this.trigger('update',stageScrollTop);return this;}},{key:'add',value:function add(els){this.canvases=this.canvases.concat(this.createCanvases((0,_helpersHelpers.$$)(els)));return this;}},{key:'remove',value:function remove(els){var _this2=this;(0,_helpersHelpers.$$)(els).forEach(function(el){var i=_this2.canvases.length;while(i--){if(el==_this2.canvases[i].img){_this2.canvases.splice(i,1);break;}}});return this;}},{key:'destroy',value:function destroy(){this.off('*');stage.off('resize',this._onResize).off('scroll',this._onScroll);return this;}},{key:'resize',value:function resize(size){var i=this.canvases.length;while(i--){var canvas=this.canvases[i];if(!canvas.isLoaded)return;canvas.update().draw(stage);}
			this.trigger('resize');return this;}},{key:'createCanvases',value:function createCanvases(els){var _this3=this;return els.map(function(el){var data=(0,_helpersHelpers.elementData)(el);return new _Canvas2['default'](el,{intensity:!(0,_helpersHelpers.isUndefined)(data.intensity)?+data.intensity:_this3.opts.intensity,center:!(0,_helpersHelpers.isUndefined)(data.center)?+data.center:_this3.opts.center});});}},{key:'opts',set:function set(opts){this._defaults={offsetYBounds:50,intensity:30,center:0.5};(0,_helpersHelpers.extend)(this._defaults,opts);},get:function get(){return this._defaults;}}]);return Parallax;})();exports['default']=Parallax;module.exports=exports['default'];},function(module,exports){'use strict';Object.defineProperty(exports,'__esModule',{value:true});exports['default']={$$:function $$(selector,ctx){var els;if(typeof selector=='string')els=(ctx||document).querySelectorAll(selector);else els=selector;return Array.prototype.slice.call(els);},$:function $(selector,ctx){return(ctx||document).querySelector(selector);},extend:function extend(src){var obj,args=arguments;for(var i=1;i<args.length;++i){if(obj=args[i]){for(var key in obj){src[key]=obj[key];}}}
	return src;},isUndefined:function isUndefined(val){return typeof val=='undefined';},elementData:function elementData(el,attr){if(attr)return el.dataset[attr]||el.getAttribute('data-'+attr);else return el.dataset||Array.prototype.slice.call(el.attributes).reduce(function(ret,attribute){if(/data-/.test(attribute.name))ret[attribute.name]=attribute.value;return ret;},{});},prefix:function prefix(obj,prop,value){var prefixes=['ms','o','Moz','webkit',''],i=prefixes.length;while(i--){var prefix=prefixes[i],p=prefix?prefix+prop[0].toUpperCase()+prop.substr(1):prop.toLowerCase()+prop.substr(1);if(p in obj){obj[p]=value;return true;}}
	return false;}};module.exports=exports['default'];},function(module,exports,__webpack_require__){'use strict';Object.defineProperty(exports,'__esModule',{value:true});var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{'default':obj};}
	function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function');}}
	var _riotObservable=__webpack_require__(3);var _riotObservable2=_interopRequireDefault(_riotObservable);var rAF=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||function(cb){setTimeout(cb,1000/60);},RESIZE_DELAY=20;var Stage=(function(){function Stage(){_classCallCheck(this,Stage);(0,_riotObservable2['default'])(this);this.resizeTimer=null;this.tick=false;this.bind();}
		_createClass(Stage,[{key:'bind',value:function bind(){var _this=this;window.addEventListener('scroll',function(){return _this.scroll();},true);window.addEventListener('mousewheel',function(){return _this.scroll();},true);window.addEventListener('touchmove',function(){return _this.scroll();},true);window.addEventListener('resize',function(){return _this.resize();},true);window.addEventListener('orientationchange',function(){return _this.resize();},true);window.onload=function(){return _this.scroll();};return this;}},{key:'scroll',value:function scroll(){var _this2=this;if(this.tick)return this;this.tick=!this.tick;rAF(function(){return _this2.update();});return this;}},{key:'update',value:function update(){this.trigger('scroll',this.scrollTop);this.tick=!this.tick;return this;}},{key:'resize',value:function resize(){var _this3=this;if(this.resizeTimer)clearTimeout(this.resizeTimer);this.resizeTimer=setTimeout(function(){return _this3.trigger('resize',_this3.size);},RESIZE_DELAY);return this;}},{key:'scrollTop',get:function get(){var top=(window.pageYOffset||document.scrollTop)-(document.clientTop||0);return window.isNaN(top)?0:top;}},{key:'height',get:function get(){return window.innerHeight;}},{key:'width',get:function get(){return window.innerWidth;}},{key:'size',get:function get(){return{width:this.width,height:this.height};}}]);return Stage;})();exports['default']=Stage;module.exports=exports['default'];},function(module,exports,__webpack_require__){(function(window,undefined){var observable=function(el){el=el||{};var callbacks={},onEachEvent=function(e,fn){e.replace(/\S+/g,fn)};el.on=function(events,fn){if(typeof fn!='function')return el;onEachEvent(events,function(name,pos){(callbacks[name]=callbacks[name]||[]).push(fn);fn.typed=pos>0});return el};el.off=function(events,fn){if(events=='*')callbacks={};else{onEachEvent(events,function(name){if(fn){var arr=callbacks[name];for(var i=0,cb;cb=arr&&arr[i];++i){if(cb==fn)arr.splice(i--,1)}}else delete callbacks[name]})}
	return el};el.one=function(events,fn){function on(){el.off(events,on);fn.apply(el,arguments)}
	return el.on(events,on)};el.trigger=function(events){var args=[].slice.call(arguments,1);onEachEvent(events,function(name){var fns=(callbacks[name]||[]).slice(0);for(var i=0,fn;fn=fns[i];++i){if(fn.busy)return;fn.busy=1;try{fn.apply(el,fn.typed?[name].concat(args):args)}catch(e){}
	if(fns[i]!==fn){i--}
	fn.busy=0}
	if(callbacks.all&&name!='all')
		el.trigger.apply(el,['all',name].concat(args))});return el};return el};if(true)
	module.exports=observable;else if(typeof define==='function'&&define.amd)
	define(function(){return observable});else
	window.observable=observable})(typeof window!='undefined'?window:undefined);},function(module,exports,__webpack_require__){'use strict';Object.defineProperty(exports,'__esModule',{value:true});var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{'default':obj};}
	function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function');}}
	var _helpersHelpers=__webpack_require__(1);var _riotObservable=__webpack_require__(3);var _riotObservable2=_interopRequireDefault(_riotObservable);var HAS_TRANSLATE_3D=(function(div){(0,_helpersHelpers.prefix)(div.style,'transform','translate3d(0, 0, 0)');return(/translate3d/g.test(div.style.cssText));})(document.createElement('div'));var Canvas=(function(){function Canvas(img,opts){_classCallCheck(this,Canvas);(0,_riotObservable2['default'])(this);this.opts=opts;this.img=img;this.wrapper=img.parentNode;this.isLoaded=false;}
		_createClass(Canvas,[{key:'load',value:function load(){var _this=this;if(!this.img.width||!this.img.width||!this.img.complete)this.img.onload=function(){return _this.onImageLoaded();};else this.onImageLoaded();return this;}},{key:'onImageLoaded',value:function onImageLoaded(){this.isLoaded=true;this.update();this.trigger('loaded',this.img);return this;}},{key:'update',value:function update(){var iw=this.img.naturalWidth||this.img.width,ih=this.img.naturalHeight||this.img.height,ratio=iw/ih,size=this.size;if(size.width/ratio<=size.height){this.img.height=size.height;this.img.width=size.height*ratio;}else{this.img.width=size.width;this.img.height=size.width/ratio;}
			this.img.style.top=-~~((this.img.height-size.height)/2)+'px';this.img.style.left=-~~((this.img.width-size.width)/2)+'px';return this;}},{key:'draw',value:function draw(stage){var size=this.size,perc=(this.offset.top+size.height*this.opts.center+stage.height/2-stage.scrollTop)/stage.height-1;perc*=this.img.height/size.height/2*this.opts.intensity;if(HAS_TRANSLATE_3D)(0,_helpersHelpers.prefix)(this.img.style,'transform','translate3d(0, '+-perc+'%, 0)');else(0,_helpersHelpers.prefix)(this.img.style,'transform','translate(0, '+-perc+'%)');return this;}},{key:'bounds',get:function get(){return this.wrapper.getBoundingClientRect();}},{key:'offset',get:function get(){return{top:this.wrapper.offsetTop,left:this.wrapper.offsetLeft};}},{key:'size',get:function get(){var props=this.bounds;return{height:props.height|0,width:props.width|0};}}]);return Canvas;})();exports['default']=Canvas;module.exports=exports['default'];}])});